# Generated by Django 5.2.9 on 2025-12-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0002_profile_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tier_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
