# Generated by Django 5.2.9 on 2025-12-13 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0003_alter_profile_tier_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rank',
        ),
    ]
