# Generated by Django 5.2.9 on 2025-12-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0004_remove_profile_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rank',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tier_amount',
            field=models.IntegerField(blank=True, choices=[(1999, 'Rank 1'), (2999, 'Rank 2'), (5999, 'Rank 3')], null=True),
        ),
    ]
